exp_name: moe-t5-base-mnli-dad-lora

model:
  t5_variant: t5-base
  learning_rate: 1e-3
  lr_scheduler: Constant

  model_modifier_config:
    base_model_type: moe
    k: 20
    moe_params_path: results/t5-base/mnli/param_split

    tuning_type: dense_act_dense_lora
    lora_rank: 32

    ckpt_path: null

data:
  dataset: mnli
  batch_size: 8
  max_source_length: 1024

trainer:
  max_epochs: 1
  val_check_interval: 3000