exp_name: t5-sst-lora

model:
  t5_variant: t5-base
  learning_rate: 1e-5
  lr_scheduler: Constant

  model_modifier_config:
    base_model_type: unmodified
    tuning_type: lora
    ckpt_path: null
    lora_rank: 32

data:
  dataset: sst2
  batch_size: 64
  max_source_length: 512

trainer:
  max_epochs: 1
  val_check_interval: 200